### ISSUE TITLE
[Bug]: [UniverseLib] Can't cache type named __c Error

### ISSUE THREAD

**Issue by Dastano** [yukieiji/UnityExplorer#17]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

MelonLoader IL2CPP CoreCLR

### Which game did this occur on?

Corepunk

### Describe the issue.

Not throwing a Error I guess? :)

### Relevant log output

```shell
[23:08:04.260] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.LightShadowCalculatorForFrustum', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[23:08:04.260] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.ObjectEffectManager', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[23:08:04.264] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.PuddleDetector', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[23:08:04.271] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppView.Extensions.AnimatedFace.UnitAnimatedFaceManager', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121

[23:08:05.204] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.AsyncUtilsUpdateMeter', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121

Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.AsyncUtilsUpdateMeter', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.Utility.SignatureHighlighter.TryGetNamespace(Type type, String& ns) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 189
   at UniverseLib.Utility.SignatureHighlighter.Parse(Type type, Boolean includeNamespace, MemberInfo memberInfo) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 106
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.AddSuggestion(Type type)
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.GetSuggestionsAsync(String input)+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
[23:08:32.301] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.LightShadowCalculatorForFrustum', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.Utility.SignatureHighlighter.TryGetNamespace(Type type, String& ns) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 189
   at UniverseLib.Utility.SignatureHighlighter.Parse(Type type, Boolean includeNamespace, MemberInfo memberInfo) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 106
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.AddSuggestion(Type type)
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.GetSuggestionsAsync(String input)+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
[23:08:32.552] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.ObjectEffectManager', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.Utility.SignatureHighlighter.TryGetNamespace(Type type, String& ns) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 189
   at UniverseLib.Utility.SignatureHighlighter.Parse(Type type, Boolean includeNamespace, MemberInfo memberInfo) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 106
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.AddSuggestion(Type type)
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.GetSuggestionsAsync(String input)+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
[23:08:33.743] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.AsyncUtilsUpdateMeter', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.Utility.SignatureHighlighter.TryGetNamespace(Type type, String& ns) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 189
   at UniverseLib.Utility.SignatureHighlighter.Parse(Type type, Boolean includeNamespace, MemberInfo memberInfo) in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 106
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.AddSuggestion(Type type)
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.GetSuggestionsAsync(String input)+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in F:\Documents\VisualStudioProject\AmongUs\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```

**Comment by Dastano** [comment]
If you need any example FIles, I am happy to upload them.

**Comment by yukieiji** [comment]
Do these errors cause any behavior problems?
When do these errors occur?

**Comment by Dastano** [comment]
I haven't found any breaking bugs yet. But I am not very deep into UE yet.

The errors happen when the game launches.

**Comment by yukieiji** [comment]
If this error is not causing you any problems, then you are fine.

**Comment by yukieiji** [comment]
close due to no reply
