### ISSUE TITLE
[Bug]: UI fails to load on startup

### ISSUE THREAD

**Issue by Babyhamsta** [yukieiji/UnityExplorer#31]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

- [ ] Yes, work fine!!

### Which release are you using?

BepInEx Unity IL2CPP CoreCLR

### Which game did this occur on?

Private - Unity 6000.0.26f1

### Describe the issue.

Even with a delay in the config, I get an error and the UI fails to load. An error is displayed in the console.

### Relevant log output

```shell
[Message: Preloader] BepInEx 6.0.0-be.725 - Client (11/11/2024 11:40:38 AM)
[Message: Preloader] Built from commit e1974e26fd7702c66b54c0d6879c90b988cc4920
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 6000.0.26f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 0.0050000004 seconds.
[Message:UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0.082 seconds.
[Message:UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[Info   :Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[Message:   BepInEx] Chainloader startup complete
[Message:     Unity] ThreadLog initialized.
[Message:     Unity] Network mode set to Client
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [UnityExplorer 4.12.2]
[Message:UnityExplorer] UnityExplorer 4.12.2 initializing...
[Message:UnityExplorer] [UniverseLib] UniverseLib 1.5.7 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Initialized Legacy Input support
[Info   :Il2CppInterop] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[Warning:UnityExplorer] [UniverseLib] Exception parsing Unity version, falling back to old AssetBundle load method...
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Could not find any iCall from list of provided signatures starting with 'UnityEngine.AssetBundle::LoadFromMemory_Internal'!
   at UniverseLib.Runtime.Il2Cpp.ICallManager.GetICallUnreliable[T](String[] possibleSignatures) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\ICallManager.cs:line 73
   at UniverseLib.AssetBundle.LoadFromMemory(Byte[] binary, UInt32 crc) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\AssetBundle.cs:line 57
   at UniverseLib.UI.UniversalUI.LoadBundle(String id) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\UI\UniversalUI.cs:line 252
   at UniverseLib.UI.UniversalUI.LoadBundle() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\UI\UniversalUI.cs:line 210
   at UniverseLib.UI.UniversalUI.Init() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\UI\UniversalUI.cs:line 108
   at UniverseLib.Universe.SetupCoroutine()+MoveNext() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Universe.cs:line 130
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```

**Comment by yukieiji** [comment]
Same bug as #21 , not a UE bug.
Therefore, it is closed.
