### ISSUE TITLE
[Bug]: - 'UnityExplorer' is missing the following dependencies: - 'UnhollowerBaseLib' v0.4.22.0

### ISSUE THREAD

**Issue by Plutoissexy** [yukieiji/UnityExplorer#38]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

- [ ] Yes, work fine!!

### Which release are you using?

MelonLoader IL2CPP net6preview

### Which game did this occur on?

Combat Masters

### Describe the issue.

[14:51:04.450] ------------------------------
[14:51:04.474] MelonLoader v0.6.6 Open-Beta
[14:51:04.475] OS: Windows 11
[14:51:04.476] Hash Code: 81E5A4A5974318B4F948B1A58B8459762E3F307B880356782FAB3857F0658A37
[14:51:04.476] ------------------------------
[14:51:04.476] Game Type: Il2cpp
[14:51:04.476] Game Arch: x64
[14:51:04.476] ------------------------------
[14:51:04.476] Command-Line: 
[14:51:04.476] ------------------------------
[14:51:04.477] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\Combat Master
[14:51:04.477] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\Combat Master
[14:51:04.477] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\Combat Master\CombatMaster_Data
[14:51:04.477] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\Combat Master\CombatMaster.exe
[14:51:04.477] Runtime Type: net6
[14:51:04.574] ------------------------------
[14:51:04.574] Game Name: Combat Master
[14:51:04.574] Game Developer: AlfaBravoInc
[14:51:04.576] Unity Version: 6000.0.28f1
[14:51:04.576] Game Version: UNKNOWN
[14:51:04.576] ------------------------------

[14:51:05.543] Preferences Loaded!

[14:51:05.556] Loading UserLibs from 'C:\Program Files (x86)\Steam\steamapps\common\Combat Master\UserLibs'...
[14:51:05.586] ------------------------------
[14:51:05.598] Melon Assembly loaded: '.\UserLibs\UniverseLib.IL2CPP.Unhollower.dll'
[14:51:05.599] SHA256 Hash: 'A0027DD953974542F779F55B4E380B8401BFE8681C0F38E1EF89B5BCC07EC804'

[14:51:05.604] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\Combat Master\Plugins'...
[14:51:05.606] 0 Plugins loaded.
[14:51:06.125] Loading Il2CppAssemblyGenerator...
[14:51:06.194] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[14:51:06.423] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/combat-master)
[14:51:06.424] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[14:51:06.425] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[14:51:06.425] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[14:51:06.425] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[14:51:06.433] [Il2CppAssemblyGenerator] Using Cpp2IL Version: 2022.1.0-pre-release.18
[14:51:06.434] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.579+9d4599dc78d69ede49a2ee96a1ccf41eec02db5b
[14:51:06.434] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 6000.0.28
[14:51:06.435] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[14:51:06.435] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[14:51:06.435] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[14:51:06.437] [Il2CppAssemblyGenerator] Checking GameAssembly...
[14:51:06.686] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[14:51:06.687] Loading Mods from 'C:\Program Files (x86)\Steam\steamapps\common\Combat Master\Mods'...
[14:51:06.704] ------------------------------
[14:51:06.725] Melon Assembly loaded: '.\Mods\UnityExplorer.ML.IL2CPP.net6preview.dll'
[14:51:06.726] SHA256 Hash: 'D830B7273FF69C4F4099654102491BF535A124DBDE3B108BD9DC11A9A5278249'

[14:51:06.934] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in future versions of MelonLoader.
- 'UnityExplorer' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.22.0
[14:51:06.946] ------------------------------
[14:51:06.948] UnityExplorer v4.12.2
[14:51:06.948] by Sinai, yukieiji
[14:51:06.948] Assembly: UnityExplorer.ML.IL2CPP.net6preview.dll
[14:51:06.948] ------------------------------
[14:51:06.949] ------------------------------
[14:51:06.949] 1 Mod loaded.

[14:51:08.622] [Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[14:51:08.850] [Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[14:51:08.929] [Il2CppInterop] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[14:51:08.973] [Il2CppInterop] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[14:51:08.983] Support Module Loaded: C:\Program Files (x86)\Steam\steamapps\common\Combat Master\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[14:51:09.008] [UnityExplorer] UnityExplorer 4.12.2 initializing...
[14:51:09.027] [UnityExplorer] [UniverseLib] UniverseLib 1.5.7 initializing...
[14:51:09.031] [UnityExplorer] System.IO.FileNotFoundException: Could not load file or assembly 'UnhollowerBaseLib, Version=0.4.22.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UnhollowerBaseLib, Version=0.4.22.0, Culture=neutral, PublicKeyToken=null'
   at UniverseLib.UniversalBehaviour.Setup()
   at UniverseLib.Universe.Init(Single startupDelay, Action onInitialized, Action`2 logHandler, UniverseLibConfig config) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Universe.cs:line 101
   at UnityExplorer.ExplorerCore.Init(IExplorerLoader loader)
   at UnityExplorer.ExplorerMelonMod.OnApplicationStart()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143

**Comment by yukieiji** [comment]
Try [UnityExplorer.MelonLoader.IL2CPP.CoreCLR](https://github.com/yukieiji/UnityExplorer/releases/download/latest/UnityExplorer.MelonLoader.IL2CPP.CoreCLR.zip).
~~However, Unity v6 shouldn't yet fully support BepInEx or MelonLoader, see #21 and #31 for details~~
