### ISSUE TITLE
[Bug]: Could not find any input module

### ISSUE THREAD

**Issue by Zephyrus2689** [yukieiji/UnityExplorer#39]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

- [X] Yes, work fine!!

### Which release are you using?

MelonLoader IL2CPP CoreCLR

### Which game did this occur on?

Slime Rancher 2

### Describe the issue.

So when i load into the game, the explorer shows on screen, but i am unable to click anything on the explorer. The highlights (cursor) in game also does not show up when hovering over buttons

### Relevant log output

```shell
UnityExplorer 4.12.2 initializing...
[UniverseLib] UniverseLib 1.5.7 initializing...
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass11_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass23_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass15_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass17_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named _AnimateItemsIn_d__4 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named _AnimateItemsOut_d__5 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass14_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named IndicatorItem Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass22_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c__DisplayClass30_0 Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] THIS WARNING IS NOT BUG!!!! DON'T REPORT THIS!!!!!
 Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[UniverseLib] Finished UniverseLib initial setup.
Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[UniverseLib] Loaded Unhollowed modules in 1.4380001 seconds.
[UniverseLib] Setup deobfuscation cache in 0.33900002 seconds.
[UniverseLib] Could not find any Input Module Type!
[UniverseLib] 	 IL2CPP method has no corresponding pointer, aborting patch of UnityEngine.AssetBundle.UnloadAllAssetBundles
[UniverseLib] Loaded modern bundle for Unity 2021.3.28f1
[UniverseLib] UniverseLib 1.5.7 initialized.
Creating UI...

UnityExplorer 4.12.2 (IL2CPP) initialized.
```

**Comment by yukieiji** [comment]
Try [this](https://github.com/yukieiji/UnityExplorer?tab=readme-ov-file#common-issues-and-solutions).
Also, please attach all logs, as stated, this warning isn't bug.

**Comment by Zephyrus2689** [comment]
changing the value to true seemed to fix the input issue and now allows me to use the mod, however when i press F7 nothing happens, if im not mistaken this should open/close UE?

**Comment by yukieiji** [comment]
Is there a conflict between in-game input and UE input key(F7)?
Please change the input key in UE or in-game

**Comment by Zephyrus2689** [comment]
I have changed the keybind to mouse 4, backspace, and keypad 5, and none of them worked. Also is there a way to use UE without it still potentially clicking buttons ingame? i tried searching for something and i keep hearing the ingame key press noises

**Comment by yukieiji** [comment]
> I have changed the keybind to mouse 4, backspace, and keypad 5, and none of them worked. Also is there a way to use UE without it still potentially clicking buttons ingame? i tried searching for something and i keep hearing the ingame key press noises

Either way, I can't do anything with just the info on the ticket.
PLEASE ATTACH ALL LOGS.

**Comment by Zephyrus2689** [comment]
[24-12-23_0-19-48.log](https://github.com/user-attachments/files/18226656/24-12-23_0-19-48.log)
[24-12-23_0-23-23.log](https://github.com/user-attachments/files/18226657/24-12-23_0-23-23.log)
[24-12-23_0-30-32.log](https://github.com/user-attachments/files/18226658/24-12-23_0-30-32.log)
[24-12-23_2-13-12.log](https://github.com/user-attachments/files/18226659/24-12-23_2-13-12.log)
[24-12-23_2-26-14.log](https://github.com/user-attachments/files/18226660/24-12-23_2-26-14.log)
[UnityExplorer 2024-12-23 000517Z.txt](https://github.com/user-attachments/files/18226661/UnityExplorer.2024-12-23.000517Z.txt)
[UnityExplorer 2024-12-23 000730Z.txt](https://github.com/user-attachments/files/18226662/UnityExplorer.2024-12-23.000730Z.txt)
[UnityExplorer 2024-12-23 001227Z.txt](https://github.com/user-attachments/files/18226663/UnityExplorer.2024-12-23.001227Z.txt)
[UnityExplorer 2024-12-23 001254Z.txt](https://github.com/user-attachments/files/18226664/UnityExplorer.2024-12-23.001254Z.txt)
[UnityExplorer 2024-12-23 001601Z.txt](https://github.com/user-attachments/files/18226665/UnityExplorer.2024-12-23.001601Z.txt)
[UnityExplorer 2024-12-23 002043Z.txt](https://github.com/user-attachments/files/18226666/UnityExplorer.2024-12-23.002043Z.txt)
[UnityExplorer 2024-12-23 002332Z.txt](https://github.com/user-attachments/files/18226667/UnityExplorer.2024-12-23.002332Z.txt)
[UnityExplorer 2024-12-23 003042Z.txt](https://github.com/user-attachments/files/18226668/UnityExplorer.2024-12-23.003042Z.txt)
[UnityExplorer 2024-12-23 021328Z.txt](https://github.com/user-attachments/files/18226669/UnityExplorer.2024-12-23.021328Z.txt)
[UnityExplorer 2024-12-23 022625Z.txt](https://github.com/user-attachments/files/18226670/UnityExplorer.2024-12-23.022625Z.txt)

This is every single log i can find in my slime rancher folder. if there are others i am unaware of please let me know

**Comment by yukieiji** [comment]
Is it possible that there are other mods installed that are causing the issue?

What did you do with the following error listed in the log?otherwise ok?
```
[02:40:28.300] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeLoadException: GenericArguments[2], 'Il2CppMonomiPark.SlimeRancher.UI.MenuNavigation.LinearNavigator+Axis', on 'Il2CppMonomiPark.SlimeRancher.UI.Adapter.AdapterView`3[T,VH,T_AXIS_LIST]' violates the constraint of type parameter 'T_AXIS_LIST'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.Utility.SignatureHighlighter.TryGetNamespace(Type type, String& ns) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 189
   at UniverseLib.Utility.SignatureHighlighter.Parse(Type type, Boolean includeNamespace, MemberInfo memberInfo) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Utility\SignatureHighlighter.cs:line 106
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.AddSuggestion(Type type)
   at UnityExplorer.UI.Widgets.AutoComplete.TypeCompleter.GetSuggestionsAsync(String input)+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```

**Comment by Zephyrus2689** [comment]
there may be mods that are interfering with it, it is the continuous sprint mod and the bettergadgets mod, and to be honest, i have no idea what i did to trigger that error. It might be possible that it was because i had the incorrect file path to dnSpy while clicking the open to dnSpy button

**Comment by yukieiji** [comment]
> there may be mods that are interfering with it, it is the continuous sprint mod and the bettergadgets mod

If these mods are in conflict, uninstall them and try them.

> i have no idea what i did to trigger that error. It might be possible that it was because i had the incorrect file path to dnSpy while clicking the open to dnSpy button

if there's no way to reproduce it, there's nothing I can do about it.

**Comment by Zephyrus2689** [comment]
Also seems there is a bug with the setting "World Mouse-Inspect keybind" as when set to mouse 3, it proceeds to generate infinite errors. as shown in this log 
[UnityExplorer 2024-12-23 035936Z.txt](https://github.com/user-attachments/files/18227594/UnityExplorer.2024-12-23.035936Z.txt)

**Comment by yukieiji** [comment]
> It seems something from both mods prevent it from being toggled. I deleted them individually, and tried each one separately with UE, the issue only stopped once both mods were gone. If i need to provide the mod dlls' i can

Even if I get the mod, I think that there is nothing I can do.
This is because UE is designed for compatibility, and the impact of fixing a bug that works with a specific mod for a specific game is too big.

 > Also seems there is a bug with the setting "World Mouse-Inspect keybind" as when set to mouse 3, it proceeds to generate infinite errors. as shown in this log

From the error log, I would judge that this is a configuration problem, not a mod bug.
The game itself suggests that it probably doesn't support the `mouse 3` input, so changing it to a generic input that any PC would have would work.
