### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SumScriptKiddie** [yukieiji/UnityExplorer#4]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

MelonLoader IL2CPP

### Which game did this occur on?

[16:07:34.629] MelonLoader v0.6.1 Open-Beta
[16:07:34.631] OS: Windows 10
[16:07:34.631] ------------------------------
[16:07:34.632] Game Type: Il2cpp
[16:07:34.632] Game Arch: x64

[16:07:34.746] Game Name: Evony: The King's Return
[16:07:34.747] Game Developer: topgamesinc
[16:07:34.749] Unity Version: 2018.4.0f1
[16:07:34.749] Game Version: 4.56.1

### Describe the issue.

Games loads fine  initially but crashes when main ui scene loads

### Relevant log output

```shell
[16:03:17.325] [UnityExplorer] UnityExplorer 4.10.0 initializing...
[16:03:17.355] [UnityExplorer] [UniverseLib] UniverseLib 1.5.4 initializing...
[16:03:17.359] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[16:03:17.876] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[16:03:17.960] [UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[16:03:17.975] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[16:03:26.337] [UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 8.458 seconds.
[16:03:26.532] [UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0.194 seconds.
[16:03:41.408] [UnityExplorer] [UniverseLib] Initialized Legacy Input support
[16:03:41.415] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Boolean Il2CppSystem.Type.op_Inequality(Il2CppSystem.Type, Il2CppSystem.Type)'.
   at UniverseLib.Universe.Patch(Type type, String methodName, MethodType methodType, Type[] arguments, MethodInfo prefix, MethodInfo postfix, MethodInfo finalizer)
   at UniverseLib.Input.CursorUnlocker.InitPatches()
   at UniverseLib.Input.CursorUnlocker.Init()
   at UniverseLib.Input.InputManager.Init()
   at UniverseLib.Universe.SetupCoroutine()+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext()
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```

**Comment by yukieiji** [comment]
I think it's an internal Il2Cpp method misreference, so either the file generated by MelonLoader or it's own installation is failing.
Do other mods work properly? If not work reinstall game and MelonLoader.

**Comment by SumScriptKiddie** [comment]
Other mods work fine on this game and i can get UnityExplorer to work on other games it just has issues with this game, let me know if there is any additional information i can help provide?

**Comment by yukieiji** [comment]
It is possible that only this game failed to generate files during MelonLoader initialization
So please try to reinstall the game and MelonLoader first.

**Comment by SumScriptKiddie** [comment]
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/309dca91-c3f3-46a1-9e6e-a5e914140f45)
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/bb67355c-273b-48a5-a10a-7b62e4d3f3a7)
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/cbbdce95-b2e3-42e0-944c-d491dd9e94b8)
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/a3cd24e3-9a64-489f-868d-8214670cfc2b)

**Comment by SumScriptKiddie** [comment]
Added images of steps just to help...

Uninstalled game,
Redownloaded fresh install of game?
Reinstalled game
Installed latest melonloader
Run game with just melonloader and no other mods (works fine)
add unity explorer and same issue happens

**Comment by yukieiji** [comment]
Will it work with older versions of MelonLoader (v5) and UnityExplorer.MelonLoader.IL2CPP?

**Comment by SumScriptKiddie** [comment]
feel like i tried that but happy to give it another whirl

**Comment by SumScriptKiddie** [comment]
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/5860c9c6-6106-4676-bbd1-c930bdbc198a)
[Latest.log](https://github.com/yukieiji/UnityExplorer/files/12842082/Latest.log)

different issue? or maybe the same issue im not sure...

**Comment by yukieiji** [comment]
> different issue? or maybe the same issue im not sure...

This seems to be an internal error in the MelonLoader process

May I ask you to create your own mod to see if there is a problem between MelonLoader and this game, and somewhere in the process write and run the code that compares the type to the type in the game?

**Comment by SumScriptKiddie** [comment]
I have made a simple mod that was working as seen below, i could also get the scenes and iterate through some of the game objects via reflect. Im not sure exactly what you mean by the type compare request?
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/6fd60434-d1fc-4493-9c29-286290a8631e)


> run the code that compares the type to the type in the game

**Comment by yukieiji** [comment]
I wanted a comparison between the class types of that game as I thought appropriate.

After some searching on my part, I found a ticket that reported a similar problem(https://github.com/LavaGang/MelonLoader/issues/524 ). according to the comments on the ticket, it isn't a bug, but a specification by Il2Cpp.

**Comment by SumScriptKiddie** [comment]
![image](https://github.com/yukieiji/UnityExplorer/assets/139295138/ab82f7ea-917e-4b18-b16c-511c1588c86b)

this script is getting objects fine


```
        public override void OnUpdate()
        {
            if (Input.GetKeyDown(KeyCode.F))
            {
                MelonLogger.Msg("F Key was Pressed");
                List<GameObject> rootObjects = new List<GameObject>();
                Scene scene = SceneManager.GetActiveScene();
                scene.GetRootGameObjects(rootObjects);
                for (int i = 0; i < rootObjects.Count; ++i)
                {
                    MelonLogger.Msg(rootObjects[i].name);
                }
            } 
        }
```


and i can also use GetComponentsInChildren to filter through them

not sure if this shows that Melonloader is working correctly?

**Comment by yukieiji** [comment]
As I said in my comment above, I think the reason is that when this game was compiled with Il2Cpp, the methods required by UnityExplorer were stripped.
So simple code may work, but the more complex code like UnityExplorer is, the more it will not work.

It is thought that if I investigate them and bypass the non-working methods for the working ones, it will work, but it takes a lot of time and effort to investigate them.

**Comment by SumScriptKiddie** [comment]
ahh ok, thanks for your help :D
