### ISSUE TITLE
[Bug]: Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by antoinechauvn** [yukieiji/UnityExplorer#42]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

- [X] Yes, work fine!!

### Which release are you using?

MelonLoader IL2CPP CoreCLR

### Which game did this occur on?

Corepunk

### Describe the issue.

When trying to start, Unity Explorer load then crash

### Relevant log output

```shell
[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[22:54:57.112] ------------------------------
[22:54:57.114] MelonLoader v0.6.6 Open-Beta
[22:54:57.115] OS: Windows 10
[22:54:57.115] Hash Code: 81E5A4A5974318B4F948B1A58B8459762E3F307B880356782FAB3857F0658A37
[22:54:57.115] ------------------------------
[22:54:57.115] Game Type: Il2cpp
[22:54:57.116] Game Arch: x64
[22:54:57.116] ------------------------------
[22:54:57.116] Command-Line:
[22:54:57.116] ------------------------------
[22:54:57.116] Core::BasePath = C:\Users\XXXXXX\Documents\Games\Corepunk\Game
[22:54:57.117] Game::BasePath = C:\Users\XXXXXXE\Documents\Games\Corepunk\Game
[22:54:57.117] Game::DataPath = C:\Users\XXXXXX\Documents\Games\Corepunk\Game\Corepunk_Data
[22:54:57.117] Game::ApplicationPath = C:\Users\XXXXXX\Documents\Games\Corepunk\Game\Corepunk.exe
[22:54:57.117] Runtime Type: net6
[22:54:57.450] ------------------------------
[22:54:57.451] Game Name: Corepunk
[22:54:57.451] Game Developer: ArtificialCore
[22:54:57.452] Unity Version: 2021.3.12f1
[22:54:57.452] Game Version: 1.0
[22:54:57.453] ------------------------------

[22:54:58.232] Preferences Loaded!

[22:54:58.242] Loading UserLibs from 'C:\Users\XXXXXX\Documents\Games\Corepunk\Game\UserLibs'...
[22:54:58.260] ------------------------------
[22:54:58.269] Melon Assembly loaded: '.\UserLibs\UniverseLib.IL2CPP.Interop.ML.dll'
[22:54:58.269] SHA256 Hash: '3890EB5E4802A08226EFF62B82B82C8F56425B580273D9D432F986CA9D97D805'

[22:54:58.275] Loading Plugins from 'C:\Users\XXXXXXE\Documents\Games\Corepunk\Game\Plugins'...
[22:54:58.277] 0 Plugins loaded.
[NewEntryPoint] PreStarting.
[22:54:59.963] Loading Il2CppAssemblyGenerator...
[22:54:59.984] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[22:55:00.105] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/corepunk)
[22:55:00.105] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[22:55:00.106] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[22:55:00.106] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[22:55:00.106] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[22:55:00.110] [Il2CppAssemblyGenerator] Using Cpp2IL Version: 2022.1.0-pre-release.18
[22:55:00.110] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.579+9d4599dc78d69ede49a2ee96a1ccf41eec02db5b
[22:55:00.111] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.12
[22:55:00.111] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[22:55:00.112] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[22:55:00.112] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[22:55:00.112] [Il2CppAssemblyGenerator] Checking GameAssembly...
[22:55:00.334] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.
[NewEntryPoint] Starting.

[22:55:00.336] Loading Mods from 'C:\Users\XXXXXX\Documents\Games\Corepunk\Game\Mods'...
[22:55:00.337] ------------------------------
[22:55:00.358] Melon Assembly loaded: '.\Mods\UnityExplorer.ML.IL2CPP.net6preview.interop.dll'
[22:55:00.358] SHA256 Hash: '9D5A3F7A38C09511EC15F824EBC35901388770BB3393AFCDDBA9F8F1FCC984D4'

[22:55:00.566] ------------------------------
[22:55:00.567] UnityExplorer v4.9.4
[22:55:00.567] by Sinai
[22:55:00.567] Assembly: UnityExplorer.ML.IL2CPP.net6preview.interop.dll
[22:55:00.568] ------------------------------
[22:55:00.568] ------------------------------
[22:55:00.569] 1 Mod loaded.

[22:55:02.105] [Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[22:55:02.269] [Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[22:55:02.327] [Il2CppInterop] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[22:55:02.380] [Il2CppInterop] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[22:55:02.389] Support Module Loaded: C:\Users\XXXXXX\Documents\Games\Corepunk\Game\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[22:55:02.425] [UnityExplorer] UnityExplorer 4.9.4 initializing...
[22:55:02.443] [UnityExplorer] [UniverseLib] UniverseLib 1.5.4.1 initializing...
[22:55:02.482] [Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[22:55:02.866] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.LightShadowCalculatorForFrustum', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:02.866] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.ObjectEffectManager', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:02.869] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.PuddleDetector', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:02.874] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppView.Extensions.AnimatedFace.UnitAnimatedFaceManager', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:02.983] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2CppAssets.Scripts.Controllers.Shared.ConfigLoader', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:02.999] [UnityExplorer] [UniverseLib] Can't cache type named __c Error: System.TypeLoadException: GenericArguments[2], 'Il2Cpp.AsyncUtilsUpdateMeter', on 'Il2Cpp.ProviderMonobeh`3[TP,TI,TC]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[22:55:03.261] [Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[22:55:03.444] [UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[22:55:03.510] [Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[22:55:03.600] [UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[22:55:05.095] [UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 1,8320001 seconds.
[22:55:05.258] [UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0,162 seconds.
[22:55:12.911] [UnityExplorer] [UniverseLib] Initialized Legacy Input support
[22:55:14.986] [Il2CppInterop] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[22:55:15.022] [UnityExplorer] [UniverseLib] Loaded modern bundle for Unity 2021.3.12f1
[22:55:15.044] [UnityExplorer] [UniverseLib] UniverseLib 1.5.4.1 initialized.
[22:55:15.046] [UnityExplorer] Creating UI...
[22:55:15.539] [UnityExplorer] UnityExplorer 4.9.4 (IL2CPP) initialized.
Fatal error. Internal CLR error. (0x80131506)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCore30Platform.CompileMethodHook(IntPtr, IntPtr, CORINFO_METHOD_INFO ByRef, UInt32, Byte* ByRef, UInt32 ByRef)
```

**Comment by yukieiji** [comment]
From the looks of it, this is not using my UE and UniverseLib.
Please reinstall my UE and UniverseLib correctly again.

**Comment by yukieiji** [comment]
Also, this “UnityExplorer.ML.IL2CPP.net6preview.interop” was created by someone else, so I cannot fix it myself
