### ISSUE TITLE
[Bug]: "Could not find any iCall" - BepInEx be.674 (Unity.IL2CPP.CoreCLR)

### ISSUE THREAD

**Issue by Babyhamsta** [yukieiji/UnityExplorer#5]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

BepInEx Unity IL2CPP CoreCLR

### Which game did this occur on?

Polytoria

### Describe the issue.

Ran into error while loading Unity Explorer in BepInEx (be.674) - Newest Edge release.
![image](https://github.com/yukieiji/UnityExplorer/assets/22938086/1ace2981-c7f8-4cac-a9c9-7289f3290e47)

### Relevant log output

```shell
[Message: Preloader] BepInEx 6.0.0-be.674 - Polytoria Client
[Message: Preloader] Built from commit 82077ec7c91c97f0e5f8ada5d178fd7ece6c0099
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2023.1.17f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [UnityExplorer 4.10.0]
[Message:UnityExplorer] UnityExplorer 4.10.0 initializing...
[Message:UnityExplorer] [UniverseLib] UniverseLib 1.5.4 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[Info   :Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[Message:   BepInEx] Chainloader startup complete
[Message:     Unity] ThreadLog initialized.
[Message:     Unity] Network mode set to Client
[Message:     Unity] ThreadedKcpTransport initialized!
[Message:     Unity] [T7] ThreadedKCP: started.
UnityEngine.Debug:Log(Object)
Mirror.WorkerThread:Guard(String)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[Message:UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 0.555 seconds.
[Message:UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0.120000005 seconds.
[Message:UnityExplorer] [UniverseLib] Initialized Legacy Input support
[Info   :Il2CppInterop] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[Warning:UnityExplorer] [UniverseLib] Exception parsing Unity version, falling back to old AssetBundle load method...
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Could not find any iCall from list of provided signatures starting with 'UnityEngine.AssetBundle::LoadFromMemory_Internal'!
   at UniverseLib.Runtime.Il2Cpp.ICallManager.GetICallUnreliable[T](String[] possibleSignatures)
   at UniverseLib.AssetBundle.LoadFromMemory(Byte[] binary, UInt32 crc)
   at UniverseLib.UI.UniversalUI.LoadBundle(String id)
   at UniverseLib.UI.UniversalUI.LoadBundle()
   at UniverseLib.UI.UniversalUI.Init()
   at UniverseLib.Universe.SetupCoroutine()+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext()
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
[Warning:     Unity] The character with Unicode value \U0001F383 was not found in the [Monsterrat Regular Shadow] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [GameName].
[Warning:     Unity] The character with Unicode value \U0001F383 was not found in the [Monsterrat Regular Shadow] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [GameName].
```

**Comment by yukieiji** [comment]
Are the other mods working properly? Especially mods that seem to have assets that exist.

**Comment by Babyhamsta** [comment]
> Are the other mods working properly? Especially mods that seem to have assets that exist.

This is the only mod I have installed and have tried.

**Comment by yukieiji** [comment]
There are several possible causes, please try the following
1. reinstall the game and BepInEx(Because the initialization process of Il2Cpp may have failed)
2. Try mods other than UnityExplorer(The game itself doesn't support mods, and some important methods may have been omitted at build time)

**Comment by Babyhamsta** [comment]
I tried reinstalling the game/BepInEx but that didn't work it provided the same error. I did test with my own plugin which does print and such, but I don't have much experience in making plugins to do what I want in-game. I am doing some testing now but there isn't a whole lot of information on the new edge templates / how to make mods for BepInEx.

**Comment by yukieiji** [comment]
Is it possible to attach the BepInEx logs from the first time it was started after reinstallation?

Also, other mods also don't work with methods around Unity, so I suspect that this game does not support the mod itself and drops the methods around Unity at build time.

**Comment by Babyhamsta** [comment]
I did test by modifying my references in my dll and did some more testing and I can get rid of the errors and call certain functions like warn and ect but I am having trouble accessing game objects. Like I said this is my first time doing something like this so I may be just doing it incorrectly.

Example:

```shell
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [ScriptDumper_Polytoria 1.0.0]
[Info   :ScriptDumper_Polytoria] Plugin ScriptDumper_Polytoria is loaded!
[Warning:     Unity] Starting Dumper! - Please standby..
[Info   :ScriptDumper_Polytoria] Main init has finished!
```

Example Code
```c
public  void init()
{
    Debug.LogWarning("Starting Dumper! - Please standby..");
    foreach (BaseScript script in Resources.FindObjectsOfTypeAll<BaseScript>())
    {
        Debug.Log("Dumping script: " + script.name);
        string path = "C:\\Users\\Admin\\AppData\\Roaming\\Polytoria\\Client\\1.3.44\\BepInEx\\plugins\\testplugin\\Scripts\\" + script.name + "_dump.txt";
        using (StreamWriter writetext = new StreamWriter(path))
        {
            writetext.WriteLine(script.source);
        }
    }
}```

**Comment by Babyhamsta** [comment]
I ended up just using HarmonyX to patch the functions I needed, you may want to look into it though as HarmonyX worked and I could reference params and ect but Unity Explorer didn't.

You can close this now if you'd like.

**Comment by yukieiji** [comment]
The logs don't indicate that the initialization process is failing, so I think the cause is that Unity functions are being deleted from the game side during the build process, and UnityExplorer is referencing them.

**Comment by yukieiji** [comment]
The basic C# library is provided by BepInEx, so it is possible to do as much as you can with that, but UnityExplorer requires Unity functions, so it would be difficult to make it work with this game.
