### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dropalways** [yukieiji/UnityExplorer#8]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

BepInEx IL2CPP

### Which game did this occur on?

1v1.lol

### Describe the issue.

im not sure if this is a melon loader bug or a unityexplorer bug, i have tried with mono and ill2cpp doesnt work with either

### Relevant log output

```shell
[06:31:07.403] ------------------------------
[06:31:07.441] MelonLoader v0.6.2 Open-Beta
[06:31:07.442] OS: Windows 11
[06:31:07.442] Hash Code: 2AD1478D8329B7784C949251EAF68C4C50E2FE9DA6CBB4BDF1DCD43E9026C63C
[06:31:07.442] ------------------------------
[06:31:07.442] Game Type: Il2cpp
[06:31:07.442] Game Arch: x64
[06:31:07.443] ------------------------------
[06:31:07.443] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL
[06:31:07.443] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL
[06:31:07.443] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\1v1_LOL_Data
[06:31:07.443] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\1v1_LOL.exe
[06:31:07.444] Runtime Type: net6
[06:31:07.547] ------------------------------
[06:31:07.547] Game Name: 1v1_LOL
[06:31:07.547] Game Developer: JustPlay.LOL
[06:31:07.549] Unity Version: 2021.3.28f1
[06:31:07.549] Game Version: 4.610
[06:31:07.549] ------------------------------

[06:31:08.210] Preferences Loaded!

[06:31:08.501] Loading UserLibss from 'C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\UserLibs'...
[06:31:08.502] ------------------------------
[06:31:08.651] Melon Assembly loaded: '.\UserLibs\UniverseLib.IL2CPP.Unhollower.dll'
[06:31:08.651] SHA256 Hash: '380a9adfc78087f19b4988a710a9af6c69df7ad6eceb731eccc29528456501c1'

[06:31:08.658] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\Plugins'...
[06:31:08.660] 0 Plugins loaded.
[06:31:09.190] [MelonStartScreen] Initializing...
[06:31:09.227] [MelonStartScreen] Using Start Screen Theme: "Default"
[06:31:09.343] [MelonStartScreen] Failed to find the signature for field m_D3D12WaitForLastPresentationAndGetTimestamp in module. Signature: 48 89 5c 24 08 57 48 81 ec 90 00 00 00 0f 29 b4 24 80 00 00 00 48 8b d9
[06:31:09.363] Loading Il2CppAssemblyGenerator...
[06:31:09.380] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[06:31:09.554] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/1v1_lol)
[06:31:09.554] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[06:31:09.555] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[06:31:09.555] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[06:31:09.556] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[06:31:09.565] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.13
[06:31:09.566] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[06:31:09.566] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.28
[06:31:09.566] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[06:31:09.567] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[06:31:09.567] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[06:31:09.567] [Il2CppAssemblyGenerator] Checking GameAssembly...
[06:31:09.752] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[06:31:09.755] Loading Mods from 'C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\Mods'...
[06:31:09.756] ------------------------------
[06:31:09.953] Melon Assembly loaded: '.\Mods\UnityExplorer.ML.IL2CPP.dll'
[06:31:09.953] SHA256 Hash: '3d08ce25e99836a16aac48efb25296f5dbcbb4fd6c9519c7129f2b6522c2e2e8'

[06:31:10.236] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'UnityExplorer' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.22.0
[06:31:10.247] ------------------------------
[06:31:10.248] UnityExplorer v4.11.0
[06:31:10.248] by Sinai, yukieiji
[06:31:10.248] Assembly: UnityExplorer.ML.IL2CPP.dll
[06:31:10.248] ------------------------------
[06:31:10.249] ------------------------------
[06:31:10.249] 1 Mod loaded.

[06:31:10.771] Class::Init signatures have been exhausted, using a substitute!
[06:31:10.804] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[06:31:10.840] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[06:31:10.842] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[06:31:10.851] Support Module Loaded: C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[06:31:10.880] [UnityExplorer] UnityExplorer 4.11.0 initializing...
[06:31:10.902] [UnityExplorer] [UniverseLib] UniverseLib 1.5.4 initializing...
[06:31:10.904] [UnityExplorer] System.IO.FileNotFoundException: Could not load file or assembly 'UnhollowerBaseLib, Version=0.4.22.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UnhollowerBaseLib, Version=0.4.22.0, Culture=neutral, PublicKeyToken=null'
   at UniverseLib.UniversalBehaviour.Setup()
   at UniverseLib.Universe.Init(Single startupDelay, Action onInitialized, Action`2 logHandler, UniverseLibConfig config)
   at UnityExplorer.ExplorerCore.Init(IExplorerLoader loader)
   at UnityExplorer.ExplorerMelonMod.OnApplicationStart()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

**Comment by yukieiji** [comment]
The UE you are using is shown as BepInEx Il2Cpp on the ticket, but the log shows the loaded UE as Melon Il2Cpp, which one are you using?
For Melon, v6.x and later, you must use [MelonLoader.Il2Cpp.CoreCLR](https://github.com/yukieiji/UnityExplorer/releases/download/v4.11.0/UnityExplorer.MelonLoader.IL2CPP.CoreCLR.zip)

**Comment by yukieiji** [comment]
Closed due to no reply.
